name: stitchup

channels:
  - loopbio
  - conda-forge
  - defaults

dependencies:
  - conda-forge::python=2.7
  - loopbio::ffmpeg=4.0.2=nonvidia_gpl*
  - loopbio::opencv=3.4.2

  - python-dateutil
  - pytz
  - tzlocal

  - pyyaml
  - numpy
  - pandas
  - bloscpack

#  - conda-forge::pyyaml=3.12
#  - conda-forge::numpy=1.14
#  - conda-forge::pandas=0.21
#  - conda-forge::bloscpack=0.10.0

#  - pytest
#  - pytest-cov
#  - pytest-pep8

  - conda-forge::cython=0.28.2
  - conda-forge::pkg-config

  - pip:
    - imgstore>=0.2.0
    - "--editable=./"
