name: stitchup

channels:
  - loopbio
  - conda-forge
  - defaults

dependencies:
  - conda-forge::python=2.7
  - loopbio::ffmpeg=4.0.2=nonvidia_gpl*
  - loopbio::opencv=3.4.3=*h6df427c*

  - python-dateutil
  - pytz
  - tzlocal

  - pyyaml
  - numpy
  - pandas
  - bloscpack

  - conda-forge::cython=0.28.2
  - conda-forge::pkg-config

  - pip:
    - imgstore>=0.2.0

